# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: James Munday
email: jmunday@perimeterinstitute.ca
description: "" # >- means to ignore newlines until "url:"
url: "https://james-munday.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username:  jekyll

repository: james-munday/james-munday.github.io

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# For Minimal Mistakes
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

minimal_mistakes_skin: "contrast"

author:
  name: "James Munday"
  avatar: "/assets/images/JamesMunday005square.jpg"
  bio: "PhD Student in Mathematical Physics." # Note: Markdown is allowed
  location: "Toronto, ON"
  email: "jmunday@perimeterinstitute.ca"
  links:
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: https://www.researchgate.net/profile/James-Munday-3
    - label: "Google Scholar"
      icon: "fab fa-fw fa-scholar"
      url: https://scholar.google.ca/citations?hl=en&user=fIvzx4cAAAAJ
    # - label: "arXiv"
    #   icon: "fab fa-fw fa-arxiv"
    #   url: https://arxiv.org/a/fritz_m_1.html

include: ["_pages"]